name: Backup Diario a Google Drive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Postgres Cliente 17 (Versión Nueva)
        run: |
          sudo apt-get install -y postgresql-common
          yes | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt-get install -y postgresql-client-17

      - name: Instalar Rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash

      - name: Configurar Rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: 1. Hacer Backup de la Base de Datos
        run: |
          FECHA=$(date +%Y-%m-%d)
          mkdir -p backups          
          
          # Usamos la ruta completa para asegurar que usa la versión 17
          /usr/lib/postgresql/17/bin/pg_dump "${{ secrets.SUPABASE_DB_URL }}" -f "backups/sm4j_db_$FECHA.sql"
          
          echo "✅ Base de datos descargada correctamente."

      - name: 2. Subir a Google Drive
        run: |
          rclone copy backups/ midrive:SM4J_Backups
          echo "✅ Backup subido a Google Drive."
